type="product"

prompt="Just My Size Wireless Bra Pack, Full Coverage, Leopard Satin, Wirefree Plus-Size Bra; aizes from 32C to 50DD; ajustable straps in the front; 90% nylon, 10% spandex; everyday bra pack and 1 satin bra; leopard print and other colors (white, nude, and others)"

human_desc="""
Just My Size Wireless Bra Pack, Full Coverage, Leopard Satin, Wirefree Plus-Size Bra, (Sizes from 32C to 50DD)

QUALITY FABRIC – The best wireless bra for large busts, this style is made from stretchy 90% nylon/10% spandex for all-around comfort.

VALUE YOU EXPECT – Each everyday women's bra pack of 1 comes with one satin bra.

FULL-COVERAGE FIT – Our soft lining is great for large busts since it provides allover coverage for that secure fit you love.

SUPPORT YOU NEED – A wide band helps shape and hold you in place for everyday wireless support that lasts. Rows of hook-and-eye closures keep you secure.

FRONT-ADJUSTABLE STRAPS – Soft, wide straps can be adjusted in the front, so no need to strain in order to find the perfect fit.

COLORS & SIZE OPTIONS – From black bras with a leopard print and other colors like white, nude, and beyond, to sizes 32C to plus sizes 50DD, we have options for everyone.
"""
