type="product"
prompt="""Mainstays Cool Mist Humidifier, 1 gallon, Black; low tank indicator; Dish washer safe; Humidity capacity: 142ml/h; Aroma tray; 3 speeds; mechanical knob; covers 320 sq. ft. area, weight: 6.33 lbs"""

human_desc="""
Mainstays Cool Mist Humidifier

The Mainstays black, 1-gallon, cool-mist humidifier uses evaporative technology to add moisture to dry rooms that have low relative humidity levels. The Mainstays black, cool-mist humidifier has a one-gallon water tank that is easy to remove for filling and is dishwasher safe for easy cleaning! The Mainstays black, 1-gallon, cool-mist humidifier is equipped with a low tank indicator with auto shut off and helps save energy when the tank is empty. Humidifiers offer many benefits to your environment, making your home a more comfortable and enjoyable place throughout the year. Consistent moisture helps to protect wood floors and furniture, and indoor plants. Reduced static electricity benefitting people, computers, and home electronics. The Mainstays black, 1-gallon, cool-mist humidifier adds moisture to the air, which makes the air feel warmer! – Now you could keep your thermostat lower while still feeling warm and comfortable during the winter months!

    Replacement Filter: Compatible with BestAir H62
    Dish washer safe
    Humidity capacity: 142ml/h
    Easy to clean
    Aroma tray available
    Empty tank protection
    Large area coverage: humidifies areas up to 320 sq. ft.
    3 speed settings -Adjustable Mechanical knob
    Evaporative technology: adds moisture to any room
    Lightweight: only 6.33 lbs
"""
