type="product"
prompt="""
oannao Silicone Cooking Utensils Kitchen Utensil Set - 446°F Heat Resistant,Turner Tongs,Spatula,Spoon,Brush,Whisk,Wooden Handles Pink Kitchen Gadgets Tools Set for Nonstick Cookware;
BPA Free, heat-resistant, non-melting, wooden handle, easy to clean
"""

human_desc="""
oannao Silicone Cooking Utensils Kitchen Utensil Set

1: The silicone cooking utensil set BPA Free, food grade silicone, does not React with Food or Beverages
2: No warping, no breaking, soft, kitchen utensils for nonstick cookware
3: The kitchen tools which one piece design with stainless steel core
4: 446°F heat resistant Wooden handle kitchen utensils for cooking,baking,mixing.14 pieces of kitchen utensils to fully meet the needs of the kitchen
5: The wooden handle is smooth and comfortable to hold, preventing heat transfer and preventing hot hands
6: Easy to clean, not recommended for dishwasher
7: Quick after-sales response (within 12 hours)

LIST OF PRODUCTS YOU WILL GET:
Deep Soup Ladle / Solid Serving Spoon
Slotted Spoon / Slotted Turner
Turner / Food Tongs
Pasta Server / Flexible Spatula
Basting Brush / Whisk
Round Spatula Turner / Large Skimmer Spoon
Small Silicone Spatula / Utensil Holder

HEAT-RESISTANT, NON-MELTING, WOODEN HANDLE - The silicone cooking utensils can withstand temperatures up to 446°F. even if they are used in a high-temperature frying environment, they will not melt or produce smoke. The wooden handle feels comfortable and strong to hold, prevents heat transfer, so you don’t have to worry about scalding the chef’s hands. these cooking utensils set is a good gift choice for mom

SAFE, BPA FREE, FOOD GRADE SILICONE,ODORLESS - The kitchen utensil set are made of high quality food grade silicone.BPA free. no harmful smell. Note: It must be soaked for half an hour when it is used for the first time, and then exposed to the air for about 3 hours, the original smell of silica gel will disappear. The silicone cooking utensil is safe to use for any type of food. These kitchen utensil set does not react with food or beverages

FULLY MEET THE NEEDS OF THE KITCHEN. NO MORE WASTE OF MONEY - These kitchen utensil sets include 9 cooking tools and 4 baking tools. A large utensil holder. Buy it at one time and get what you need in the kitchen. No more waste of money. Deep Soup Ladle, Solid Serving Spoon, Slotted Spoon, Flexible Spatula, Round Spatula, Pasta Server, Slotted Turner, etc. These silicone kitchen utensil perfectly protect the surface of the non-stick pan from scratches

NO GAPS, NO FOOD IS CAPTURED, EASY TO CLEAN - Add stainless steel to each cooking utensil to maintain an initial optimal memory state. Never warp. And full of flexibility. One-piece molding without any gaps to capture food. Make cleaning easier. Note: Because of the wooden handle, these kitchen tools are not suitable for prolonged soaking in water and dishwasher cleaning

QUICK AFTER-SALES RESPONSE AND PRECAUTIONS : QUICKLY ANSWER ANY OF YOUR QUESTIONS - Whenever you tell us the challenges you face through Buyer Page. we will continue to listen carefully. We value you and your open and honest questions, which can help us focus on your most urgent needs. Your question will generally respond quickly within 12 hours
"""
