type="product"
prompt="""LK 2 Pack for Google Pixel 8 Screen Protector with 2 Pack Camera Lens Protector, HD Ultra-thin, 9H Hardness Tempered Glass Screen Protector for Pixel 8; fingerprint Compatible; Military-grade shatterproof; screen protection and camera lens protection;
original visual experience; high-response haptic touch"""

human_desc = """
LK 2 Pack for Google Pixel 8 Screen Protector with 2 Pack Camera Lens Protector, HD Ultra-thin, 9H Hardness Tempered Glass Screen Protector for Pixel 8; fingerprint Compatible

* [Compatible & Cost-effective] LK Google Pixel 8 Screen Protector and Camera Lens Protector are specially designed for Google Pixel 8. LK is Committed to providing a one-stop purchase experience. The Package comes with 2 Pack Google Pixel 8 tempered glass screen protectors & 2 pack camera lens protectors and full accessories for installation.

* [Military-grade shatterproof] Google Pixel 8 Screen Protector made of 9H super strong military explosion-proof glass with edge strengthening design, ensures that every corner of the screen is protected. Its hardness is much higher than other products on the market.
  
* [All-Round Protection] We provide screen protection and camera lens protection at the same time for your Google Pixel 8 - The screen protector provides strong protection for your Google Pixel 8. The camera lens protector is made from superior 9H tempered glass that is scratch and shatterproof protecting your camera from scratches and high impact drops.

* [High Definition & Touch Sensitive] LK Google Pixel 8 High Transparency Screen Protector with ultra-thin design, brings bright and colorful image quality, keeping the original visual experience for you. High-response haptic touch technology makes you feel like a bare screen during use.

* [Lifetime Service] We always aim at providing excellent products & service to customers. If you have any questions before or after your purchase, please feel free to contact us, we will reply to you within 24 hours.
"""
